In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [9]:
import os

print(os.listdir('/content'))

['.config', 'archive (1).zip', 'sample_data']


In [15]:
import zipfile
import pandas as pd

with zipfile.ZipFile('/content/archive (1).zip', 'r') as zip_ref:
    zip_ref.extract('Reviews.csv', '/content/')

In [16]:
df = pd.read_csv('/content/Reviews.csv', nrows=50000)

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (50000, 10)


,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...


In [17]:
light_reviews = df[df["Text"].str.contains(r"\blight\b",
                                           case=False,
                                           na=False)]

print("Number of reviews containing 'light':", len(light_reviews))
light_reviews["Text"].head(20)

Number of reviews containing 'light': 1415


,Text
2,This is a confection that has been around a fe...
238,A very delicate green tea with a smooth light ...
269,This is a delicious sugar. It has a pretty lig...
396,Arrowhead Mills Buttermilk Pancake mix is my f...
404,A good tasting light chip that has some value ...
462,Kettle Chips flavors can be hit or miss. Some...
466,"I'm addicted to salty and tangy flavors, so wh..."
467,These Honey Dijon chips bring a terrific balan...
486,Just got this order and it is ok. A bit light ...
556,DEfintely not as tasty as the Madhouse Munchie...


In [24]:
for i, review in enumerate(light_reviews["Text"].head(30)):
    print(f"\nReview {i+1}")
    print(review)


Review 1
This is a confection that has been around a few centuries.  It is a light, pillowy citrus gelatin with nuts - in this case Filberts. And it is cut into tiny squares and then liberally coated with powdered sugar.  And it is a tiny mouthful of heaven.  Not too chewy, and very flavorful.  I highly recommend this yummy treat.  If you are familiar with the story of C.S. Lewis' "The Lion, The Witch, and The Wardrobe" - this is the treat that seduces Edmund into selling out his Brother and Sisters to the Witch.

Review 2
A very delicate green tea with a smooth light taste and an subtle floral tones and no bitter aftertaste.<br /><br />In the 20+ years we have been drinking Ahmad teas not even once have we been disappointed. The superb quality of Ahmad teas has remained consistent throughout the years.<br /><br />I am so happy to find Ahmad teas available here (thanks Amazon!) because only a few stores carry it in my area and they are quite a few miles away. The current deal for the 

In [20]:
sentences = [
    "This olive oil is wonderful and very light on the stomach.",
    "The packaging was broken and let too much light inside the box.",
    "I prefer this brand because it is a light and healthy snack."
]

In [21]:
vectorizer = CountVectorizer()

doc_term_matrix = vectorizer.fit_transform(sentences)

dense_matrix = doc_term_matrix.toarray()

print("Dense Matrix:")
print(dense_matrix)

Dense Matrix:
[[1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
 [1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]]


In [22]:
vec_1 = dense_matrix[0]
vec_2 = dense_matrix[1]
vec_3 = dense_matrix[2]

print("Vector 1:", vec_1)
print("Vector 2:", vec_2)
print("Vector 3:", vec_3)

Vector 1: [1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
Vector 2: [1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
Vector 3: [1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]


In [23]:
similarity_1_2 = np.dot(vec_1, vec_2)
similarity_1_3 = np.dot(vec_1, vec_3)

print("\nSimilarity Scores")
print("------------------")
print("Sentence 1 vs Sentence 2:", similarity_1_2)
print("Sentence 1 vs Sentence 3:", similarity_1_3)


Similarity Scores
------------------
Sentence 1 vs Sentence 2: 4
Sentence 1 vs Sentence 3: 4
